# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from mhyt import yt_download
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 321)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.principal = QtWidgets.QFrame(self.centralwidget)
        self.principal.setGeometry(QtCore.QRect(0, 0, 391, 321))
        self.principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principal.setObjectName("principal")
        self.label = QtWidgets.QLabel(self.principal)
        self.label.setGeometry(QtCore.QRect(190, 40, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_link = QtWidgets.QLineEdit(self.principal)
        self.txt_link.setGeometry(QtCore.QRect(70, 130, 281, 21))
        self.txt_link.setObjectName("txt_link")
        self.txt_titulo = QtWidgets.QLineEdit(self.principal)
        self.txt_titulo.setGeometry(QtCore.QRect(70, 170, 281, 21))
        self.txt_titulo.setObjectName("txt_titulo")
        self.pushButton = QtWidgets.QPushButton(self.principal)
        self.pushButton.setGeometry(QtCore.QRect(200, 210, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.principal)
        self.label_3.setGeometry(QtCore.QRect(30, -10, 161, 121))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.principal)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.principal)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.principal)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 210, 49, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.txt_mensagem = QtWidgets.QLineEdit(self.principal)
        self.txt_mensagem.setGeometry(QtCore.QRect(110, 270, 161, 21))
        self.txt_mensagem.setAcceptDrops(True)
        self.txt_mensagem.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_mensagem.setAutoFillBackground(False)
        self.txt_mensagem.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.txt_mensagem.setText("")
        self.txt_mensagem.setFrame(False)
        self.txt_mensagem.setObjectName("txt_mensagem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ### Botão Download ###
        self.pushButton.clicked.connect(self.download)

### Função Download Video ###
    def download(self):
        self.txt_mensagem.setText('Download em andamento') ## Mensagem de início do download
        if self.radioButton.isChecked() == True:
            try:
                url = self.txt_link.text()
                titulo = self.txt_titulo.text()
                titulo_mp4 = titulo + '.mp3'
                yt_download(url, titulo_mp4, ismusic = True, codec = "mp3")
            except:
                pass
        elif self.radioButton_2.isChecked() == True:
            url = self.txt_link.text()
            titulo = self.txt_titulo.text()
            titulo_mp4 = titulo + '.mp4'
            yt_download(url, titulo_mp4)
        self.txt_link.setText('') ## Apaga texto link
        self.txt_titulo.setText('') ## Apaga texto titulo
        self.txt_mensagem.setText('Download encerrado') ## Mensagem de início do download

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Download"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/youtube/YouTube.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Título:"))
        self.label_2.setText(_translate("MainWindow", "Link:"))
        self.radioButton.setText(_translate("MainWindow", "mp3"))
        self.radioButton_2.setText(_translate("MainWindow", "mp4"))


### IMAGENS ###
import youtube


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
